#!/bin/bash

echo "🚀 AURA Landing Page - Testing & Deployment Guide"
echo "=================================================="

echo ""
echo "📦 1. Install Dependencies"
echo "npm install"

echo ""
echo "🔧 2. Run Development Server"
echo "npm run dev"
echo "   → Open http://localhost:5173"

echo ""
echo "🏗️ 3. Build for Production"
echo "npm run build"
echo "   → Creates dist/ folder"

echo ""
echo "👀 4. Preview Production Build"
echo "npm run preview"
echo "   → Test production build locally"

echo ""
echo "🌐 5. Deployment Options"
echo ""
echo "Vercel (Recommended):"
echo "  1. Connect GitHub repo to Vercel"
echo "  2. Auto-deploy on push"
echo "  3. Custom domain support"
echo ""
echo "Netlify:"
echo "  1. Drag & drop dist/ folder"
echo "  2. Or connect GitHub repo"
echo "  3. Auto-deploy on push"
echo ""
echo "GitHub Pages:"
echo "  1. npm run build"
echo "  2. Push dist/ to gh-pages branch"
echo "  3. Enable Pages in repo settings"

echo ""
echo "✅ Components Included:"
echo "  ✓ Navbar (sticky with blur)"
echo "  ✓ Hero (with dashboard preview)"
echo "  ✓ Features (6 cards with animations)"
echo "  ✓ How It Works (timeline)"
echo "  ✓ Dashboard Preview (large showcase)"
echo "  ✓ Tech Stack (badges + GitHub CTA)"
echo "  ✓ Footer (complete with links)"
echo "  ✓ Scroll animations"
echo "  ✓ Responsive design"

echo ""
echo "🎨 Design Features:"
echo "  ✓ Dark theme (#0B0F19)"
echo "  ✓ Glassmorphism effects"
echo "  ✓ Gradient highlights"
echo "  ✓ Smooth animations"
echo "  ✓ Professional typography"

echo ""
echo "📱 Responsive Breakpoints:"
echo "  • Mobile: < 768px"
echo "  • Tablet: 768px - 1024px"
echo "  • Desktop: > 1024px"

echo ""
echo "🔗 Links to Update:"
echo "  • GitHub: https://github.com/Ankitcodes30/AURA.git"
echo "  • Live Demo: [Add your deployment URL]"
echo "  • Dashboard Image: /src/assets/dashboard-preview.png.png"

echo ""
echo "🚀 Ready to launch your AURA landing page!"